version: "3.7"

services:
  nanos:
    image: local-speculos
    volumes:
      - ./src:/speculos/src
      - ./build/nanos2/bin/app.elf:/speculos/apps/syscoin.elf
    ports:
      # - "1234:1234" # gdb
      - "5002:5002" # api
      - "40000:40000" # apdu
      - "41000:41000" # vnc
    command: "--model nanosp ./apps/syscoin.elf --seed secret --display headless --apdu-port 40000 --vnc-port 41000 --api-port 5002"
    # Add `--vnc-password "<password>"` for macos users to use built-in vnc client.

  stax:
    build: .github/workflows
    # image: syscoin-speculos
    volumes:
      - ./src:/speculos/src
      - ./build/stax/bin/app.elf:/speculos/apps/syscoin.elf
    ports:
      - "5004:5000" # api
      - "40004:40004" # apdu
    entrypoint:  ["python", "./speculos.py"]
    command: "--model stax ./apps/syscoin.elf --seed secret --display headless --api-port 5000"
    # Add `--vnc-password "<password>"` for macos users to use built-in vnc client.
