name: Build custom speculos-bitcoin image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build and push ledger-app-builder image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build and push speculos-syscoin to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: .github/workflows/Dockerfile
          repository: osiastedian/ledger-app-syscoin/speculos-syscoin
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_sha: true
          tags: latest
          build_args: TARGETPLATFORM=linux/amd64
